// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Defensive guard: if env vars are missing or still contain surrounding quotes
// (a common Vercel misconfiguration), strip them and fall back to a placeholder
// so createClient never throws and the portfolio still renders with static data.
function cleanEnv(val: string | undefined): string {
  if (!val) return '';
  // Strip surrounding double-quotes that can appear when the value is set
  // in Vercel's UI as: "https://…" instead of: https://…
  return val.replace(/^"|"$/g, '').trim();
}

const supabaseUrl = cleanEnv(SUPABASE_URL) || 'https://placeholder.supabase.co';
const supabaseKey = cleanEnv(SUPABASE_PUBLISHABLE_KEY) || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});